version: '3.8'

services:

  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    build:
          context: ../backend
          dockerfile: Dockerfile
    restart: always
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
    env_file:
      - ../.env
#   command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 foodgram.wsgi" # NEW

  frontend:
    build:
          context: ../frontend
          dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - frontend

volumes:
  static:
  media:
  db_data: