version: '3.8'

volumes:
  static:
  media:
  db_data:

services:
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    image: qorgiz/foodgram_backend
    restart: always
    volumes:
      - static:/app/backend_static/
      - media:/app/media/
    depends_on:
      - db
    env_file:
      - ../.env

  frontend:
    image: qorgiz/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static:/var/html/backend_static/
      - media:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - frontend
