# Generated by Django 4.2.5 on 2023-10-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cooking_time_minutes',
            new_name='cooking_time',
        ),
    ]
