# Generated by Django 4.2.5 on 2023-09-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_is_favorited_recipe_is_in_shopping_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_favorited',
            new_name='is_favorite',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes_images/'),
        ),
    ]
