# Generated by Django 4.2.5 on 2023-09-26 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_is_favorited_recipe_is_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color_code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(regex='^[-a-zA-Z0-9_]+$')]),
        ),
    ]
