# Generated by Django 4.2.5 on 2023-09-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_unit_of_measurement_recipeingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_favorite',
            new_name='is_favorited',
        ),
    ]
