# Generated by Django 4.2.5 on 2023-10-04 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipeingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes_images/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default=112233, max_length=7, validators=[django.core.validators.RegexValidator(message='Введите правильный hex-код цвета (например, "#RRGGBB").', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
