# Generated by Django 4.2.5 on 2023-09-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_favorite_recipe_alter_favorite_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
    ]
