# Generated by Django 4.2.5 on 2023-10-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
    ]
