# Generated by Django 4.2.5 on 2023-09-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_recipe_options_recipe_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',)},
        ),
    ]
