# Generated by Django 4.2.5 on 2023-10-11 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_remove_ingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Введите правильный hex-код цвета (например, "#RRGGBB"). Либо такой hex-код уже существует.', regex='^#([A-F0-9]{6}|[A-F0-9]{3})$')]),
        ),
    ]
