# Generated by Django 4.2.5 on 2023-09-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_recipe_is_favorited'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
