# Generated by Django 4.2.5 on 2023-10-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_favorites_remove_user_shopping_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь'},
        ),
        migrations.AlterModelOptions(
            name='userfollow',
            options={},
        ),
    ]
