# Generated by Django 4.2.5 on 2023-09-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_bio_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'Email уже используется'}, help_text='Укажите свой email', max_length=254, unique=True, verbose_name='Почта'),
        ),
    ]
