# Generated by Django 4.2.5 on 2023-09-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipeingredient_measurement_unit'),
        ('users', '0021_userfollow_delete_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='carts', to='recipes.recipe'),
        ),
    ]
