# Generated by Django 4.2.5 on 2023-09-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_favorite_user'),
        ('users', '0022_user_shopping_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='users_favorite', to='recipes.recipe'),
        ),
    ]
