# Generated by Django 4.2.5 on 2023-09-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_favorite_recipe'),
        ('users', '0025_remove_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='recipes.recipe'),
        ),
    ]
